FROM flarum-prod-flarum:latest

WORKDIR /opt/flarum

RUN composer require justoverclock/flarum-ext-hashtag

# Install login2see plugin from GitHub fork
RUN composer config repositories.login2see vcs https://github.com/rainbowtrash2333/flarum-login2see \
    && composer require rainbowtrash2333/flarum-login2see:@dev

COPY extensions/translate_flarum/flarum-ext-translate /my-extensions/translate_flarum

RUN composer config repositories.twikura-translate path /my-extensions/translate_flarum \
    && composer require twikura/flarum-ext-translate:@dev

# Build JS frontend assets for the translate extension
RUN apk add --no-cache nodejs npm
WORKDIR /my-extensions/translate_flarum/js
RUN npm ci
RUN npm run build
WORKDIR /opt/flarum

RUN rm -rf ~/.composer/cache
